### ISSUE TITLE
Segfault after upgrading

### ISSUE THREAD

**Issue by chrisnicola** [sass/sassc-rails#58]
I recently updated Rails for some CVE patches which had the side effect of updating Sprockets to 3.0.

As I result I'm also updating sassc-rails to 1.2. After doing all of this I'm getting a segfault.

```
14:15:20 rails.1   | ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin14]
14:15:20 rails.1   |
14:15:20 rails.1   | -- Crash Report log information --------------------------------------------
14:15:20 rails.1   |    See Crash Report log file under the one of following:
14:15:20 rails.1   |      * ~/Library/Logs/CrashReporter
14:15:20 rails.1   |      * /Library/Logs/CrashReporter
14:15:20 rails.1   |      * ~/Library/Logs/DiagnosticReports
14:15:20 rails.1   |      * /Library/Logs/DiagnosticReports
14:15:20 rails.1   |    for more details.
14:15:20 rails.1   |
14:15:20 rails.1   | -- Control frame information -----------------------------------------------
14:15:20 rails.1   | c:0218 p:---- s:1290 e:001289 CFUNC  :compile_data_context
14:15:20 rails.1   | c:0217 p:0284 s:1286 e:001285 METHOD /usr/local/Cellar/rbenv/0.4.0/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sassc-1.8.4/lib/sassc/engine.rb:39
14:15:20 rails.1   | c:0216 p:0008 s:1277 e:001276 BLOCK  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sassc-rails-1.2.0/lib/sassc/rails/template.rb:27
14:15:20 rails.1   | c:0215 p:0060 s:1275 e:001274 METHOD /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/utils.rb:154
14:15:20 rails.1   | c:0214 p:0154 s:1269 e:001268 METHOD /usr/local/Cellar/rbenv/0.4.0/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sassc-rails-1.2.0/lib/sassc/rails/template.rb:26
14:15:20 rails.1   | c:0213 p:0011 s:1261 e:001260 METHOD /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/sass_processor.rb:30
14:15:20 rails.1   | c:0212 p:0055 s:1257 e:001256 METHOD /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75
14:15:20 rails.1   | c:0211 p:0017 s:1250 e:001249 BLOCK  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57 [FINISH]
14:15:20 rails.1   | c:0210 p:---- s:1246 e:001245 CFUNC  :reverse_each
14:15:20 rails.1   | c:0209 p:0042 s:1243 e:001242 METHOD /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56
14:15:20 rails.1   | c:0208 p:0335 s:1236 e:001235 METHOD /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134
14:15:20 rails.1   | c:0207 p:0077 s:1217 e:001216 BLOCK  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60
14:15:20 rails.1   | c:0206 p:0042 s:1212 e:001211 METHOD /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318
14:15:20 rails.1   | c:0205 p:0138 s:1203 e:001202 METHOD /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44
14:15:20 rails.1   | c:0204 p:0014 s:1195 e:001191 BLOCK  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20 [FINISH]
14:15:20 rails.1   | c:0203 p:---- s:1188 e:001187 CFUNC  :yield
```

I'm not really sure where to go with this from here, so I'm hoping someone might have a suggestion.

**Comment by chrisnicola** [comment]
After a bit of testing, this segfault seems to happen whenever it encounters any kind of asset pipeline helper, including `image_tag` or `asset_url`

**Comment by bolandrm** [comment]
To fix this in the short term, you can fix this by downgrading sprockets-rails:

`gem 'sprockets-rails', '< 3.0.0'`

**Comment by chrisnicola** [comment]
Thanks that works for the time being.

**Comment by carols10cents** [comment]
Hm, I'm trying to switch from sass-rails (4.0.5) to sassc-rails (1.2.0), and I'm seeing this same segmentation fault, at sassc-1.8.4/lib/sassc/engine.rb:39, but I'm on sprockets-rails 2.2.4 (and sprockets 2.12.4), which is a version of sprockets-rails that is less than 3.0.0, so the suggested fix does not work for me.

I also tried upgrading to sprockets-rails 2.3.3 and sprockets 2.12.4 and I'm still getting the segfault :( 

Is there any other information I could provide that would be useful? Do you have any other suggested debugging steps? I have a lot of CSS...

**Comment by bolandrm** [comment]
Hey @carols10cents - Sorry for the delayed response, I missed your comment somehow.  I just released sassc-ruby 1.8.5, could you try setting that in your gemfile?

Also, is there any way you can update to Sprockets 3.5?  That could be the issue as well.

**Comment by carols10cents** [comment]
@bolandrm Thank you for getting back to me! :heart: Don't worry about the delay :)

Between when I posted that and today, I did get my app upgraded to sprockets 3.5.2, but I was still getting the segfault if I switched to sassc-- but sassc 1.8.5 has fixed it!

**Comment by bolandrm** [comment]
Perfect!  Closing this issue then
